collapse
-i
/home/zhangjy/data/00.Archive/2103-CIRI-long/Nprot/input.txt
-o
/tmp/CIRI_long
-p
CIRI-long
-t
16
-r
/data/public/database/GENCODE/Mouse_Release_M25/_BWAindex/GRCm38.p6.genome.fa
-a
/data/public/database/GENCODE/Mouse_Release_M25/gencode.vM25.annotation.gtf
-c
/data/public/database/circAtlas/mouse_bed_v2.0.bed


call
-i
/home/zhangjy/data/00.Archive/2103-CIRI-long/Nprot/02.Porechop/trimmed.fastq.gz
-o
/tmp/CIRI_long_call
-r
/data/public/database/GENCODE/Mouse_Release_M25/_BWAindex/GRCm38.p6.genome.fa
-p
CIRI-long
-a
/data/public/database/GENCODE/Mouse_Release_M25/gencode.vM25.annotation.gtf
-t
16
-c
/data/public/database/circAtlas/mouse_bed_v2.0.bed